version: 2.1

orbs:
  android: circleci/android@1.0.3

commands:
  setup-project:
    steps:
      - checkout
      - android/accept-licenses

  assemble:
    parameters:
      to:
        type: string
    steps:
      - run:
          name: "Run << parameters.to >>:assembleRelease"
          command: ./gradlew << parameters.to >>:assembleRelease

  lint:
    parameters:
      to:
        type: string
    steps:
      - run:
          name: "Run << parameters.to >>:lint"
          command: ./gradlew << parameters.to >>:lint
      - store_artifacts:
          path: << parameters.to >>/build/reports
          destination: reports/<< parameters.to >>
      - store_test_results:
          path: << parameters.to >>/build/test-results

  unit-test:
    parameters:
      to:
        type: string
    steps:
      - run:
          name: "Run << parameters.to >>:testDebugUnitTest"
          command: ./gradlew << parameters.to >>:testDebugUnitTest
      - store_artifacts:
          path: << parameters.to >>/build/reports
          destination: reports/<< parameters.to >>
      - store_test_results:
          path: << parameters.to >>/build/test-results

  publish-artifacts:
    steps:
      - run:
          name: "Publish Artifacts to Github"
          command: ./gradlew publish

jobs:
  build:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - setup-project
      - assemble:
          to: "core"
      - android/save-build-cache
      - android/save-gradle-cache

  lint:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - checkout
      - android/restore-build-cache
      - android/restore-gradle-cache
      - lint:
          to: "core"

  unit-test:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - checkout
      - android/restore-build-cache
      - android/restore-gradle-cache
      - unit-test:
          to: "core"

  publish:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - checkout
      - android/restore-build-cache
      - android/restore-gradle-cache
      - publish-artifacts

workflows:
  version: "1.0.0"

  default:
    jobs:
      - build:
          filters:
            branches:
              only: master

      - lint:
          requires:
            - build

      - unit-test:
          requires:
            - build

      - publish:
          requires:
            - lint
            - unit-test
          filters:
            branches:
              only: master