version: 2.1

orbs:
  android: circleci/android@1.0.3

commands:
  setup-project:
    steps:
      - checkout
      - android/accept-licenses

  build-module:
    parameters:
      id:
        type: string
      flavor:
        type: string
        default: ""
    steps:
      - run:
          name: "Run Gradle Task << parameters.id >>:assemble<< parameters.flavor >>"
          command: ./gradlew << parameters.id >>:assemble<< parameters.flavor >>

  lint:
    parameters:
      module:
        type: string
    steps:
      - run:
          name: "Run << parameters.module >>:lint"
          command: ./gradlew << parameters.module >>:lint
      - store_artifacts:
          path: << parameters.module >>/build/reports
          destination: reports/<< parameters.module >>
      - store_test_results:
          path: << parameters.module >>/build/test-results

  unit-test:
    parameters:
      module:
        type: string
    steps:
      - run:
          name: "Run << parameters.module >>:testDebugUnitTest"
          command: ./gradlew << parameters.module >>:testDebugUnitTest
      - store_artifacts:
          path: << parameters.module >>/build/reports
          destination: reports/<< parameters.module >>
      - store_test_results:
          path: << parameters.module >>/build/test-results

  publish-artifacts:
    steps:
      - run:
          name: "Publish Artifacts to Github"
          command: ./gradlew publish --continue

jobs:

  build:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - setup-project
      - android/restore-gradle-cache
      - build-module:
          id: "core"
      - build-module:
          id: "oauth2client"
      - android/save-build-cache
      - android/save-gradle-cache

  lint:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - checkout
      - android/restore-build-cache
      - android/restore-gradle-cache
      - lint:
          module: "core"

  unit-test:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - checkout
      - android/restore-build-cache
      - android/restore-gradle-cache
      - unit-test:
          module: "core"

  publish-maven:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - checkout
      - android/restore-build-cache
      - android/restore-gradle-cache
      - publish-artifacts

workflows:
  version: 2

  branch-test:
    jobs:
      - build:
          filters:
            branches:
              only: /(feature\/.*)|(hotfix\/.*)|(release\/.*)/
      - lint:
          requires:
            - build
      - unit-test:
          requires:
            - build

  publish-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d.\d.\d/
      - publish-maven:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d.\d.\d/
          requires:
            - build
