version: 2.1

orbs:
  android: circleci/android@0.2.3

commands:
  download-gradle-dependencies:
    steps:
      - run:
          name: "Downloading Gradle Dependencies"
          command: ./gradlew androidDependencies

  save-gradle-cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle
          key:
            jars{{ checksum "build.gradle" }}
            - {{ checksum  "core/build.gradle" }}

  restore-gradle-cache:
    steps:
      - restore_cache:
          paths:
            - ~/.gradle
          key:
            jars{{ checksum "build.gradle" }}
            - {{ checksum  "core/build.gradle" }}

  setup-g-services:
    steps:
      - run:
          name: "Setup google-services.json"
          command: echo $G_SERVICES | base64 -di > ~/project/app/google-services.json

  setup-publishing:
    steps:
      - run:
          name: "Setup publish.properties"
          command: echo $PUBLISH_PROPS | base64 -di > ~/project/buildSystem/publishing.properties

  setup-project:
    steps:
      - checkout
      - setup-g-services
      - setup-publishing
      - android/restore-build-cache
      - restore-gradle-cache

  lint:
    parameters:
      to:
        type: string
    steps:
      - run:
          name: "Run << parameters.to >>:lint"
          command: ./gradlew << parameters.to >>:lint
      - store_artifacts:
          path: << parameters.to >>/build/reports
          destination: reports/<< parameters.to >>
      - store_test_results:
          path: << parameters.to >>/build/test-results

  unit-test:
    parameters:
      to:
        type: string
    steps:
      - run:
          name: "Run << parameters.to >>:testDebugUnitTest"
          command: ./gradlew << parameters.to >>:testDebugUnitTest
      - store_artifacts:
          path: << parameters.to >>/build/reports
          destination: reports/<< parameters.to >>
      - store_test_results:
          path: << parameters.to >>/build/test-results

  publish-artifacts:
    steps:
      - run:
          name: "Uploading Artifacts to Bintray"
          command: ./gradlew bintrayUpload

jobs:
  build:
    executor:
      name: android/android
      sdk-version: "29"
    steps:
      - checkout
      - setup-g-services
      - setup-publishing
      - download-gradle-dependencies
      - save-gradle-cache
      - android/save-build-cache

  lint:
    executor:
      name: android/android
      sdk-version: "29"
    steps:
      - setup-project
      - lint:
          to: "core"

  unit-test:
    executor:
      name: android/android
      sdk-version: "29"
    steps:
      - setup-project
      - unit-test:
          to: "core"

  publish:
    executor:
      name: android/android
      sdk-version: "29"
    steps:
      - setup-project
      - publish-artifacts

workflows:
  version: "0.0.1"

  default:
    jobs:
      - build:
          filters:
            branches:
              only: master

      - lint:
          requires:
            - build

      - unit-test:
          requires:
            - build

      - publish:
          requires:
            - lint
            - unit-test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/