version: 2.1

orbs:
  android: circleci/android@1.0.3

commands:
  setup-project:
    steps:
      - checkout
      - android/accept-licenses

  assemble-debug:
    parameters:
      to:
        type: string
    steps:
      - run:
          name: "Run << parameters.to >>:assembleDebug"
          command: ./gradlew << parameters.to >>:assembleDebug

  assemble-release:
    parameters:
      to:
        type: string
    steps:
      - run:
          name: "Run << parameters.to >>:assembleRelease"
          command: ./gradlew << parameters.to >>:assembleRelease

  lint:
    parameters:
      to:
        type: string
    steps:
      - run:
          name: "Run << parameters.to >>:lint"
          command: ./gradlew << parameters.to >>:lint
      - store_artifacts:
          path: << parameters.to >>/build/reports
          destination: reports/<< parameters.to >>
      - store_test_results:
          path: << parameters.to >>/build/test-results

  unit-test:
    parameters:
      to:
        type: string
    steps:
      - run:
          name: "Run << parameters.to >>:testDebugUnitTest"
          command: ./gradlew << parameters.to >>:testDebugUnitTest
      - store_artifacts:
          path: << parameters.to >>/build/reports
          destination: reports/<< parameters.to >>
      - store_test_results:
          path: << parameters.to >>/build/test-results

  publish-artifacts:
    steps:
      - run:
          name: "Publish Artifacts to Github"
          command: ./gradlew publish

jobs:

  build-debug:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - setup-project
      - assemble-debug:
          to: "core"
      - android/save-build-cache:
          cache-prefix: "debug"
      - android/save-gradle-cache:
          cache-prefix: "debug"

  build-release:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - setup-project
      - assemble-release:
          to: "core"
      - android/save-build-cache:
          cache-prefix: "release"
      - android/save-gradle-cache:
          cache-prefix: "release"

  lint:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - checkout
      - android/restore-build-cache:
          cache-prefix: "debug"
      - android/restore-gradle-cache:
          cache-prefix: "debug"
      - lint:
          to: "core"

  unit-test:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - checkout
      - android/restore-build-cache:
          cache-prefix: "debug"
      - android/restore-gradle-cache:
          cache-prefix: "debug"
      - unit-test:
          to: "core"

  publish-maven:
    executor:
      name: android/android
      sdk-version: "23"
    steps:
      - checkout
      - android/restore-build-cache:
          cache-prefix: "release"
      - android/restore-gradle-cache:
          cache-prefix: "release"
      - publish-artifacts

workflows:
  version: "1.0.0"

  branch-test:
    jobs:
      - build-debug:
          filters:
            branches:
              only: /(feature\/.*)|(hotfix\/.*)|(release\/.*)/
      - lint:
          requires:
            - build-debug
      - unit-test:
          requires:
            - build-debug

  publish-release:
    jobs:
      - build-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d.\d.\d/
      - publish-maven:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d.\d.\d/
          requires:
            - build-release
